### ISSUE TITLE
Layout Builder in Widget Area creates new CSS File for every page

### ISSUE THREAD

**Issue by Onatcer** [siteorigin/so-widgets-bundle#1361]
We recently discovered a that the Siteorigin Plugin writes a lot of CSS files into the storage path, more than usual and more than we see on other wordpress instances. After investigation we found that this happens because there are SiteOrigin Image and SiteOrigin Icon Elements nested in a Siteorigin Builder in a Widget Area.

We also got a Siteorigin Social Media Icons Element in a Widget Area which seems to handle this correctly as it only creates a CSS File with the hash (f.e. sow-social-media-buttons-flat-e197534e2b65.css) and does not create a new CSS File for every Page it is embedded with (f.e. sow-icon-default-b7241b644c90-108804.css)

Is there a solution for this or do you have a pointer how to fix this?

**Comment by AlexGStapleton** [comment]
Hi @Onatcer,

I've been able to replicate this issue. I've identified a fix and I'll reply with links to patched versions of both Page Builder and SiteOrigin Widgets Bundle that resolve this issue.

Kind regards,
Alex

**Comment by AlexGStapleton** [comment]
This issue is resolved by https://github.com/siteorigin/so-widgets-bundle/pull/1362 and https://github.com/siteorigin/siteorigin-panels/pull/905.

I've prepared you patched versions of Page Builder and Widgets Bundle. You can download them via the following links:

[siteorigin-panels.2.12.6.1.zip](https://drive.google.com/uc?id=1qrwtVuLr93F76ZCaNqXFsW-JFSvd3nos)
[so-widgets-bundle.1.21.0.1.zip](https://drive.google.com/uc?id=107VJ_Xh7Y3fUqCUcIjKdIIHuLhsQ-7gX)

Before proceeding, do a backup.

Navigate to **Plugins > Installed Plugins** and deactivate Page Builder by SiteOrigin and SiteOrigin Widgets Bundle, then delete both. Scroll to the top of the page and click **Add New**, **Upload Plugin** and upload Page Builder. When prompted, activate it. Go to **Plugins > Add New** and click **Upload Plugin**. Upload SiteOrigin Widgets Bundle and when prompted, activate it.

I recommend manually clearing the contents of **wp-content/uploads/siteorigin-widgets** and then navigating around your website. This will allow you to identify if these changes worked as expected.

**Comment by AlexGStapleton** [comment]
Hi,

Sorry, there was an issue with the previously provided build. Please use the following builds instead:

[siteorigin-panels.2.12.6.2.zip](https://drive.google.com/uc?id=1ypKYcQ2bRQuo6RskTF57_zdquab9O8Nl)
[so-widgets-bundle.1.21.0.2.zip](https://drive.google.com/uc?id=1GnO4bCtmSXWWzWX7vCzRpQYjvF2Ux8bD)

Kind regards,
Alex

**Comment by AlexGStapleton** [comment]
Hi,

The correct Page Builder build is:

[siteorigin-panels.2.12.6.1.zip](https://drive.google.com/uc?id=1qrwtVuLr93F76ZCaNqXFsW-JFSvd3nos)

Kind regards,
Alex

**Comment by Onatcer** [comment]
Panels seems to work fine but i get an error in the widget bundle 

Fatal error: Uncaught Error: Class 'Less_Parser' not found in /var/www/html/wp-content/plugins/so-widgets-bundle/base/inc/lessc.inc.php:122 Stack trace: #0 /var/www/html/wp-content/plugins/so-widgets-bundle/base/siteorigin-widget.class.php(901): SiteOrigin_LessC->compile('\n\n.so-widget-co...') #1 /var/www/html/wp-content/plugins/so-widgets-bundle/base/siteorigin-widget.class.php(754): SiteOrigin_Widget->get_instance_css(Array) #2 /var/www/html/wp-content/plugins/so-widgets-bundle/base/siteorigin-widget.class.php(308): SiteOrigin_Widget->save_css(Array) #3 /var/www/html/wp-content/plugins/so-widgets-bundle/base/siteorigin-widget.class.php(188): SiteOrigin_Widget->generate_and_enqueue_instance_styles(Array) #4 /var/www/html/wp-content/plugins/siteorigin-panels/inc/renderer.php(591): SiteOrigin_Widget->widget(Array, Array) #5 /var/www/html/wp-content/plugins/siteorigin-panels/inc/renderer.php(913): SiteOrigin_Panels_Renderer->the_widget(Array, Array, 1, 0, 0, true, false, 301, '') #6 /var/www/html/wp-content/plugins/siteori in /var/www/html/wp-content/plugins/so-widgets-bundle/base/inc/lessc.inc.php on line 122

**Comment by AlexGStapleton** [comment]
@Onatcer That type of error is a sign of an incomplete plugin install. Please try reinstalling the provided SiteOrigin Widgets Bundle patched version.
