### ISSUE TITLE
Image Grid: Image field allows user to upload non-image files also

### ISSUE THREAD

**Issue by ernilambar** [siteorigin/so-widgets-bundle#192]
May be it is good to restrict to `image` only in Image Grid widget. Add `'library' => 'image'` ??

**Comment by braamgenis** [comment]
While you might be able to upload any file types, you shouldn't be able to select them for use in the image grid. This behaviour is fairly normal when using the media library. Are you able to use non-image files in the image grid?

**Comment by ernilambar** [comment]
I am allowed to add non-image file. In the front end, empty div with class `sow-image-grid-image` comes for that.

**Comment by braamgenis** [comment]
Hmmm, that's strange. The media selection field we use restricts the library to images as you suggested, by default. Could you please give an example of the file type you're able to select as an image in the image grid?

**Comment by ernilambar** [comment]
I tested with regular Microsoft Word doc file.

Currently it is like this.
https://github.com/siteorigin/so-widgets-bundle/blob/develop/widgets/image-grid/image-grid.php#L66

Default value of `library` parameter is `file`. https://siteorigin.com/docs/widgets-bundle/form-building/form-fields/#heading-media To restrict for images only, may be we need to explicitly add `'library' => 'image'` for `image` field.

**Comment by braamgenis** [comment]
Ok, so that `'type' => 'media'` is what let's us know what we need to create media field. Unfortunately, the docs are a bit confusing there. They are referring to the default of the WordPress Media Library. Where the media field has [default options](https://github.com/siteorigin/so-widgets-bundle/blob/develop/base/inc/fields/media.class.php#L44) containing `'library' => 'image'`. This doesn't restrict the file types which may be uploaded, but rather is a filter on the query used to display items for selection in the library.

There appears to be an issue in the WordPress Media Library where if you upload an item, it is immediately selected after being uploaded, even though it doesn't actually appear in the library for the specified type. So if you upload a file and immediately click 'Set Media' it will attempt to use that attachment. I'm not sure there's anything we can do about this, but will investigate when there's some time.

**Comment by AlexGStapleton** [comment]
I've had a look at this issue and I can confirm what Braam is saying. I've looked into this and this isn't something we can directly fix and will need to be fixed directly by WordPress. I'm going to close this - sorry mate.
