### ISSUE TITLE
At smaller resolutions the widget interface will be covered by the sidebar when opened

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#276]
At smaller resolutions, the widgets interface for some of our widgets will be covered by the sidebar.  This issue can be fixed by simply increasing the z-index of the widget to something over 9990.
![](https://i.imgur.com/ptTivc5.gif)

z-index fix:
![](https://i.imgur.com/WkjKfcs.gif)

**Comment by AlexGStapleton** [comment]
To clarify, the width of the browser in the above gifs is 1276x943. So while small, it's not absurdly small.

**Comment by gregpriday** [comment]
This would technically be a WordPress issue. We could hack this, but it would be better for everyone if this was fixed in WordPress itself - https://make.wordpress.org/core/handbook/testing/reporting-bugs/

Although, my guess is that the focus right now is on widgets in the customizer, so this might not get immediate attention.
