### ISSUE TITLE
Hero Widget Button: Algin has no affect unless specially aligned via editor

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#316]
The hero widget button alignment settings don't do anything unless specifically aligned via the WordPress editor (as in, text-algin: center;). This issue seems to be related to [this display: inline-block](https://github.com/siteorigin/so-widgets-bundle/blame/develop/widgets/hero/styles/default.less#L77) as removing it resolves it in all of my test cases.

Reference GIF:
![](https://i.imgur.com/TInfTyt.gif)

This GIF is of me disabling the aforementioned display: inline-block;

[Reference Layout](https://u.teknik.io/VJ7DT.json)

**Comment by gregpriday** [comment]
As far as I remember, that was the point with the Hero Image Widget. The alignment should be handled in the editor, rather than in the button sub widget.

Unfortunately, there's no easy way for us to remove that alignment field from the button sub widget. Maybe we'll add something like this in the future.

**Comment by Misplon** [comment]
I'll add a note in the documentation.

**Comment by Misplon** [comment]
[Slack chat](https://siteorigin.slack.com/archives/D02T14XBJ/p1525942584000380)
