### ISSUE TITLE
get_widget_form performance issue

### ISSUE THREAD

**Issue by daviedR** [siteorigin/so-widgets-bundle#397]
Hi,

As suggested on my previous ticket #329, currently I use `get_widget_form` function for all my custom widgets. This allows me to populate posts as choices in a `<select>` field.

I tried to populate WooCommerce product posts into a `<select>` field's options. This process makes my site performance really slow, both in front-end (view page) and admin page (edit page). Turns out, the `get_widget_form` function is called even when you are not in edit page.

This is a serious performance issue. In front-end, there is no need to get all available choices of a `<select>` field (a lot of queries might be performed here), all it needs is the value or default value.

Any thought?

**Comment by braamgenis** [comment]
Hi @daviedR Thanks for reporting! We'll look into this soon and see if there's a way we can improve performance around the `get_widget_form` function.

**Comment by gregpriday** [comment]
Hi @daviedR 

We'll look at a way of refactoring this, for now, you could only populate your select field options when `is_admin()` is `true`.

**Comment by abooker819** [comment]
Hi @daviedR 
Would you mind sharing this code or what you did. I'm stuck in the same situation and their documentation is of little help.

**Comment by AlexGStapleton** [comment]
Really sorry for the delay. We're currently looking over all of the overlooked issues and I've been tasked with handling this one. I've run a few tests to map out if this change is something we should look at introducing.

During my testing, I found that the performance improvements as a result of this change were outweighed by the need for duplicating certain data as the performance improvement were very minimal (in the range of 0.0100 - 0.0150). This lack of overall difference is as a result of the caching of the form options. I suspect this caching was introduced as a result of this thread and it simply wasn't posted about - I'm _really_ sorry about that!

We're always looking for ways to improve performance and will always consider suggestions/feedback, but this change sadly isn't worthwhile due to other performance changes made since the initial posting.
