### ISSUE TITLE
Hero widget inside of a layout slider will use the layout slider's height after setup.

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#409]
A hero widget inside of a layout slider will use the layout slider's height after setup (ie. once the slide changes).

[Example](http://alex.siteorigin.net/layout-slider-slide-height-issue/)

**Comment by braamgenis** [comment]
Is this a common use case? I agree that it should be fixed, but don't want to prioritize it unless it's something we see often, as it could be quite a time consuming fix.

**Comment by AlexGStapleton** [comment]
It's not all that common but I've seen a recent increase of usage of the layout slider so it might start to become common. Regardless, #307 is a bigger deal and should absolutely be prioritized as it is common but people just don't know about it.

**Comment by gregpriday** [comment]
@AlexGStapleton We've since taken siteorigin.net down, so I can't see the example. How common did this issue land up being?

If you think it's common enough for us to invest the 4-6 hours of work I'd guess it'd take to fix it, then I'll take a look.

It does sound like something we could quite easily call a limitation or justifiable behaviour though, unless it really does break the design in certain situations?

**Comment by AlexGStapleton** [comment]
This is honestly never come up. I'm going to close this and we'll re-open this if this comes up again.
