### ISSUE TITLE
Editor Widget: Add some sort of draft saving in the background

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#464]
If possible, look at adding some sort of background draft saving for Editor widget editing only. Something similar to Gmail. We had a case where a user didn't update the widget while editing and lost work.

**Comment by gregpriday** [comment]
So this could be something that we add either on a widget level or to specific fields. A sort of dedicated history browser for a widget that's saved in browser storage.

**Comment by AlexGStapleton** [comment]
I really like the idea of specific fields with the ability for widgets to disable or enable this sort of thing. It'll prevent unnecessary saving of redundant data.

**Comment by braamgenis** [comment]
Nice idea! :+1:  It depends on how long we want the data to be available. If it's enough to just keep it around for a session (i.e. until the browser tab is closed) I don't think we have to be too concerned about how much we store. Otherwise if we want to store data across browser sessions, we should probably be more strict about only storing the necessary / required data.

**Comment by gregpriday** [comment]
The main use case for this would be a crashed page or some other form of lost work. We could just keep a single instance of the widget's data (along with its ID) in browser storage, and then do a WordPress-editor style "there's a more up to date version of this widget in your browser storage" or something.

If we're just storing a single instance, that means we wouldn't need to worry too much about space. We could also have everything expire after a few days.
