### ISSUE TITLE
Widget UI bug on smaller screens

### ISSUE THREAD

**Issue by andrejarh** [siteorigin/so-widgets-bundle#574]
There appears to be an issue with the Widgets created with the widget bundle on smaller screens.
The calculation of width with js is not good. The open widget size is too big and the content is not visible - it is hidden behind the WordPress menu.
Please check the video with visual explanation here:
http://jmp.sh/G40Uhjq

The issue affects the screen sizes below 1080 px. Which is approximately 5% of desktop setups (source: https://www.w3schools.com/browsers/browsers_display.asp)

**Comment by gregpriday** [comment]
I'd actually argue this is a UI bug with the core WordPress widgets interface. We're passing a width of 800 px [here](https://github.com/siteorigin/so-widgets-bundle/blob/develop/base/siteorigin-widget.class.php#L64), and it's handling the rest. So technically any widget with a high width will have this overlap, not just Widgets Bundle widgets.

We do have a min-width being set [here](https://github.com/siteorigin/so-widgets-bundle/blob/develop/base/css/admin.less#L54). We added that to fix an issue with the customizer. In the widgets interface though, that min width isn't even being hit, and we could add some extra CSS to remove this from the widgets interface.

My guess is this isn't something core WordPress would fix because of the focus on using the Customizer for adding widgets now.

Unfortunately, there's not much we can do outside of something really hacky. Best would be to report this to the WordPress UI team to see if they're willing to fix it.
