### ISSUE TITLE
TinyMCE field: NextGen Gallery visual shortcode not formatting correctly

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#594]
[NextGen Gallery](https://wordpress.org/plugins/nextgen-gallery/) includes functionality called [Visual Shortcodes](https://www.imagely.com/help-test-visual-shortcodes/). For whatever reason, it doesn't work in the SiteOrigin Editor widget but it does work with the [Black Studio TinyMCE Widget](https://en-au.wordpress.org/plugins/black-studio-tinymce-widget/).

We should take a look to see if this is something we can fix. I suspect the difference is that we use the Editor JS API while I don't think Black Studio does so there's likely an additional step we have to take.

WordPress:
![](https://i.imgur.com/bKDaGbV.png)

SiteOrigin Editor:
![](https://i.imgur.com/FKdvGjV.png)

**Comment by Misplon** [comment]
@AlexGStapleton Please, can you confirm this still a problem. Thanks.

**Comment by AlexGStapleton** [comment]
Can confirm this still doesn't work.

**Comment by Misplon** [comment]
The issue pertains to the shortcode preview in the Editor widget. Here is how its meant to look:

![68747470733a2f2f692e696d6775722e636f6d2f624b44614762562e706e67](https://user-images.githubusercontent.com/789159/58827765-19c8d100-8644-11e9-820a-7f9f827f4c78.png)

And here is how it looks:

![Edit_Page_‹_SiteOrigin_—_WordPress](https://user-images.githubusercontent.com/789159/58827798-2fd69180-8644-11e9-8bc7-690bc5398e21.png)

The Edit and Delete links work. The shortcode works. The issue is just the visual representation of the shortcode.
