### ISSUE TITLE
Yoast Readability issues with some of our widets

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#618]
A recent Yoast change has introduced a major change in how they analyze text for readability and this change doesn't play well certain of our widgets such as the SiteOrigin Button or SiteOrigin Image widget.

This issue is handled gracefully in the free version but the premium version of Yoast will basically fall over. Please note that I don't have access to Yoast Premium to test against - we should be able to request a copy.

![](https://i.imgur.com/1cwT7Cb.png)

For reference, here's a copy of the text:

> An error occurred in the 'fleschReadingEase' assessment
> FeedbackAn error occurred in the 'textSentenceLength' assessment
> FeedbackAn error occurred in the 'textTransitionWords' assessment
> FeedbackAn error occurred in the 'passiveVoice' assessment
> FeedbackAn error occurred in the 'sentenceBeginnings' assessment

**Comment by AlexGStapleton** [comment]
Reported in this thread: https://wordpress.org/support/topic/yoast-incompatibility-with-siteorigin-widget/

**Comment by AlexGStapleton** [comment]
This issue still occurs in the recent Yoast update but they've changed things so it degrades more gracefully so it's less of a serious issue.

![](https://i.imgur.com/wswiHMT.png)

![](https://i.imgur.com/1WFUlHy.png)

**Comment by braamgenis** [comment]
Thanks for updating. This is being caused by Yoast doing an AJAX call to fetch processed shortcodes and replace the raw shortcode with the processed one in the content. However because it's out of the normal context it doesn't perform some escaping we require and so it doesn't succeed when trying to replace the raw shortcode and instead just removes the shortcode tags as unrecognized. Going to put this on ice for the time being.

**Comment by Misplon** [comment]
Thanks guys, we'll work this here: https://github.com/siteorigin/siteorigin-panels/issues/499.
