### ISSUE TITLE
Accordion: Add option to automatically add paragraphs

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#666]
We should add an option to automatically add paragraphs to accordion items. For example, the following HTML:

```
Test

&nbsp;

Test

&nbsp;

Test

&nbsp;

Test
<h1>Test</h1>
Test
```

Will look like this on output:

![](https://i.imgur.com/4yrd2Cp.png)

**Comment by Misplon** [comment]
@AlexGStapleton Please, can you chat with Braam and ask him if he's like to proceed with this or just get his thoughts.

**Comment by braamgenis** [comment]
So we're already supposed to be doing this by default for TinyMCE fields when using the Visual editing tab, but it turns out there was a bug preventing it from happening. IMO it makes sense that we don't automatically do this for the Text (HTML) tab to try avoid surprising the user with unexpected results.

We added this option in the Editor widget to try stay aligned with how the core editor worked, but they since removed the option and my guess would be for similar reasons, i.e. switching between the Visual and Text tabs had unexpected results.

There is perhaps more to discuss around how we could go about adding the ability to do things like `wp_make_content_images_responsive`. Feel free to hit me up on Slack if/when you want to chat about it.

**Comment by braamgenis** [comment]
So we're already supposed to be doing this by default for TinyMCE fields when using the Visual editing tab, but it turns out there was a bug preventing it from happening ([fixed now](https://github.com/siteorigin/so-widgets-bundle/commit/fc5a7eb8033eb127b99e623a36825dc1fab4bce1)). IMO it makes sense that we don't automatically do this for the Text (HTML) tab to try avoid surprising the user with unexpected results.

We added this option in the Editor widget to try stay aligned with how the core editor worked, but they since removed the option and my guess would be for similar reasons, i.e. switching between the Visual and Text tabs had unexpected results.

There is perhaps more to discuss around how we could go about adding the ability to do things like `wp_make_content_images_responsive`. Feel free to hit me up on Slack if/when you guys want to chat about it.

**Comment by AlexGStapleton** [comment]
Ah. I wasn't aware of that issue. I'm completely fine with everything you've stated.
Should we instead just directly [wpautop](https://github.com/siteorigin/so-widgets-bundle/pull/734/files#diff-1296e8b8daa9763a58d7eef32b8322a4R228) against the accordion item content? I ask because without it new lines aren't rendered.

**Comment by braamgenis** [comment]
Yep, that's what I was trying to say. We _do_ [run](https://github.com/siteorigin/so-widgets-bundle/blob/7b909ddf9d09841dbc94851baeb619cdc17bc1c8/base/inc/fields/tinymce.class.php#L507) `wpautop` by default for _all_ TinyMCE fields when the editor is on the Visual tab. The previously mentioned bug was making it seem as if TinyMCE fields were always on the Text tab and so never ran `wpautop`, but that should be fixed now if you pull the latest from develop.

**Comment by AlexGStapleton** [comment]
Oh. Well, in that case, I'm going to close this.
