### ISSUE TITLE
Beaver Builder (2.0/2.1): Layout Builder buttons don't work

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#699]
The button in the Layout Builder/Layout Slider/Accordion/tab widgets to open the layout builder don't work. There is no JavaScript error.

**Comment by braamgenis** [comment]
For now this is unsupported. The problem is that PB scripts and assets aren't enqueued in the Beaver Builder front-end editing context and it's not trivial to get them enqueued. I've added messages in the Layout Builder/Slider widgets and just removed the option in Premium the Accordion/Tabs widgets. We can look at adding support for this later, but closing for now.
