### ISSUE TITLE
widget field not working

### ISSUE THREAD

**Issue by Jursdotme** [siteorigin/so-widgets-bundle#7]
I am trying to add a custom widget and want to add a layout module in a repeater field. I am getting this error when trying to use the example code (or any variation of it) from the docs:

```
Fatal error: Class 'SiteOrigin_Widget_Button_Widget' not found in /Users/Rasmus/Desktop/toro/wp-content/plugins/so-widgets-bundle/base/siteorigin-widget.class.php on line 923
```

It fails even if this is the only field in the widget or if i change the button widget to any other widget.

**Comment by Jursdotme** [comment]
If i change the class to `SiteOrigin_Panels_Widgets_Layout` (The one i actually want) i get the following error:
```
Fatal error: Call to undefined method SiteOrigin_Panels_Widgets_Layout::form_options() in /Users/Rasmus/Desktop/toro/wp-content/plugins/so-widgets-bundle/base/siteorigin-widget.class.php on line 925
`

**Comment by gregpriday** [comment]
Awesome to hear you're building a custom widget. Braam and I are busy working on extending the developer docs to make this a little bit easier.

At the moment, the Widgets Bundle doesn't actually support having arbitrary widgets as widget fields. So that's why you're having a problem with using `SiteOrigin_Panels_Widgets_Layout`. All sub widgets must be instances of `SiteOrigin_Widget`. I've logged this as an issue on our issue tracker - we'll add some checks for that.

That said, I chatted to Braam and we love the idea of having a Page Builder layout as a field option in the Widgets Bundle. It might just be possible in a future update ;)

As for the fatal error with `SiteOrigin_Widget_Button_Widget`. Are you by any chance using a modified version of the Widgets Bundle? Extending widgets assumes you have a fairly standard copy of the original Widgets Bundle plugin installed.

**Comment by gregpriday** [comment]
Wait, it would be possible to get that error if the button widget isn't active in Plugins > SiteOrigin Widgets. If you look at the initialize function of the Call-to-action widget, you'll see that it has the following code.

`
if( !class_exists('SiteOrigin_Widget_Button_Widget') ) {
	include plugin_dir_path( __FILE__ ) . '../so-button-widget/so-button-widget.php';
	siteorigin_widget_register( 'button', realpath( plugin_dir_path( __FILE__ ) . '../so-button-widget/so-button-widget.php' ) );
}
`

This ensures the `SiteOrigin_Widget_Button_Widget` class is available even if it's not active. We'll look at a way of adding this to the base SiteOrigin_Widget, but for now, each widget must make sure its sub widgets are available.

**Comment by Jursdotme** [comment]
Your right about the deactivated widget. That fixed the "Button_Widget" example.

Im looking forward to seeing if you figure out a way to add layout builder to a repeater.

As a "next best thing" do you know if it would be possible to add a WYSIWYG editor to a repeater?

**Comment by gregpriday** [comment]
Adding a TinyMCE WYSIWYG field type to the Widgets Bundle core is something
we've also spoken about here at SiteOrigin. It's on the roadmap, we just
can't say when it'll be available.

It really would be powerful field to have.

On Mon, Apr 20, 2015 at 12:46 PM, Rasmus Jürs <notifications@github.com>
wrote:

> Your right about the deactivated widget. That fixed the "Button_Widget"
> example.
>
> Im looking forward to seeing if you figure out a way to add layout builder
> to a repeater.
>
> As a "next best thing" do you know if it would be possible to add a
> WYSIWYG editor to a repeater?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/siteorigin/so-widgets-bundle/issues/7#issuecomment-94419860>
> .
>



-- 
I make free WordPress themes
http://siteorigin.com

**Comment by Jursdotme** [comment]
Sounds great. Looking forward to seeing what you guys come up with.
