### ISSUE TITLE
New Repeater items do not retain any data until the page has been saved

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#768]
For whatever reason, adding a new hero frame will save the addition of a new frame but not any adjustments to the newly added frame. You'll be able to adjust the frame upon reloading the page.

I suspect this issue may be related to [the recent repeater adjustments](https://github.com/siteorigin/so-widgets-bundle/commit/9412458dbb34ebca8eb2717057401ad6f93dbbd0).

[Here's an example video](https://drive.google.com/a/siteorigin.com/uc?id=1Ndsb3EyNkpBm_EYBJ8cmxs9-gNQN1VQ5) of this issue. Here's what I did in the video:

**Comment by AlexGStapleton** [comment]
This also appears to be affecting the Price Table Widget.

**Comment by AlexGStapleton** [comment]
This appears to affect most repeaters. Oddly, one user reported it not affecting the slider widget for them but I suspect this was purely by luck. I'm going to update this issue title to reflect this.

**Comment by SamuelNCarvalho** [comment]
Has this been fixed? I'm having the same problem with this version of so-widgets-bundle.
I have the following widget: [https://codeshare.io/2WjERE](https://codeshare.io/2WjERE)
And the following field: [https://codeshare.io/2WjERE](https://codeshare.io/aYrEXQ)

When saving the post, it is creating a new copy of the added item. And the field I created is not persisting the data, because after adding the data-name it is removing the name of the html.

Could you help me, I'm having big problems because of this bug.

**Comment by AlexGStapleton** [comment]
This fix hasn't been released yet. It's slated for release version shortly.

**Comment by LinuZitac** [comment]
I'm having the same issues as SamuelNCarvalho above. It's actually almost the exakt same issue. A custom field with an array of images selectable in a <select>.
When placed as a form field it works, but when i add it to a repeater i get the same issues. 
Due to changelog i can see this something about repeaters was fixed by 1.13.3 (16:th nov). 

Since 16:th there has been 3 more releases. Does any of them contain a solution for this issue?

**Comment by AlexGStapleton** [comment]
The fix for this issue was released in 1.13.3. Does this issue occur in the latest update for you (1.14.1)?
If this issue remains, can you please provide me with a copy of your widgets code so I can run some tests?

**Comment by LinuZitac** [comment]
I added it to pastebin:
The widget: https://pastebin.com/gz7n32yt
The field: https://pastebin.com/AVX9M05Q

You may have to fiddle with the comments for get_widget_form() in the widget file, turning the single/repeater on and off and all that. :)

**Comment by AlexGStapleton** [comment]
Can you please provide me with a copy of your complete code? Ideally, I need to avoid differences in how the provided code is loaded.
