### ISSUE TITLE
Contact Form: Add reCAPTCHA V3 support

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#822]
It doesn't appear as though reCAPTCHA V3 is currently working with the Contact Form widget. Let's add support if possible. Thanks.

**Comment by braamgenis** [comment]
Oh, nice. Looks like they did a proper update. I would rather call this an enhancement though, as recaptcha v2 seems to still work as is. Will try get to this soon.

**Comment by gregpriday** [comment]
reCAPTCHA V3 is practically a completely different product to V2. It doesn't exactly replace it.

It requires a big change in the backend to deal with scores from 0-1, instead of just true and false that v2 gives. V2 is still better suited to our simple contact form, so I'd rather not implement this.

**Comment by braamgenis** [comment]
Ah, yeah, v2 isn't [going away](https://developers.google.com/recaptcha/docs/faq):
>reCAPTCHA v2 is not going away! We will continue to fully support and improve security and usability for v2.
