### ISSUE TITLE
Icons showing ampersand

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#828]
We've had a handful of reports of icons showing an ampersand. Font Awesome works but IcoMoon and Elegant Theme Line Icons are not.

<img width="342" alt="ampersand" src="https://user-images.githubusercontent.com/789159/52631443-78b4df80-2ec7-11e9-9821-6f239227e60c.png">

The following has been tried:

JSON layout sent to us. We can't recreate locally.
Deactivate all non-SiteOrgin plugins and switch to default theme. Issue persists.
Re-save the widget. Issue persists.
Check that the icon preview shows in the widget. It does.

Here are two of the support threads:
https://siteorigin.com/thread/elegant-themes-line-icons-replaced-by
https://wordpress.org/support/topic/icomoon-icons-display-as/

**Comment by Misplon** [comment]
@AlexGStapleton If there is any info or feedback that I've left out, please add when able. Thanks :)

**Comment by gregpriday** [comment]
Maybe it has something to do with those font's filenames? Can we find out where these sites are hosted? Are they on Windows servers or something?

**Comment by Misplon** [comment]
The most recent site we're looking at appears to be hosted with https://futurequest.net/Services/Compare/. Getting error logs might be the next best step though, in line with your idea.

**Comment by AlexGStapleton** [comment]
When this issue occurs the & is set as the literal icon while normally the icon Unicode is output. Manually updating the icon with a valid Unicode restores the icon.

It's outputting as:
![](https://vgy.me/k1PJDN.png)

When it should be:
![](https://vgy.me/M2x97R.png)

[Video example of updating the icon](https://drive.google.com/a/siteorigin.com/uc?id=16TQxhn15TfpWEUIhp9bhrOiylIDKCMRJ)

**Comment by gregpriday** [comment]
That helps. I'll take a look.

**Comment by gregpriday** [comment]
This is a PHP 5.2 only issue. Probably because it's not quite as good at handling character encoding.

It's  more than likely related to https://github.com/siteorigin/so-widgets-bundle/commit/12e4e71fd008c9408ca54fa7aaee7e66bd037992#diff-42c27934512039924cc8e53dcad763cdR99 - we're using a `$unicode` variable now, instead of just echoing out the value from the `$widget_icon_families` array. So somewhere along the lines, the encoding is being lost and it's just echoing the first character, which is always an `&`.

@braamgenis I am happy to mark this as `wont-fix` unless you see something easy. It's a non-breaking limitation. We can just have users roll back to an older version of WB, or ask their hosts to update to a supported version of PHP.

**Comment by Misplon** [comment]
If we could look to see if there is an easy way, that would be great. There is going to be a long tail of support threads raised due to this.

**Comment by gregpriday** [comment]
There you go brah

**Comment by Misplon** [comment]
Power!
