### ISSUE TITLE
Maps: Add documentation on gesture handling

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#840]
<img width="435" alt="edit_page_ _siteorigin_ _wordpress" src="https://user-images.githubusercontent.com/789159/53632632-23decc00-3c1e-11e9-9b9a-ac6131113ade.png">

Add documentation on gesture handling

**Comment by Misplon** [comment]
https://developers.google.com/maps/documentation/javascript/interaction

**Comment by Misplon** [comment]
@braamgenis I'll leave this one open for me as it's a new setting so I need to add a section to the maps docs page on it.

**Comment by braamgenis** [comment]
Just note that while this is a "new" setting, it's technically a migration of previous settings ([draggable](https://developers.google.com/maps/documentation/javascript/reference/map#MapOptions.draggable) and [scrollwheel](https://developers.google.com/maps/documentation/javascript/reference/map#MapOptions.scrollwheel)) that were removed due to deprecation by Google. So if those were mentioned in the docs we should probably mention that.

**Comment by Misplon** [comment]
Epic, thanks, will do!

**Comment by Misplon** [comment]
The Maps documentation page has been updated with all the new settings added since it was initially published.

https://siteorigin.com/widgets-bundle/google-maps-widget/

I'll update the documentation further (Gesture Handling) once the release is out.

**Comment by Misplon** [comment]
Docs have been updated with the new options from `1.15.3`.
