### ISSUE TITLE
Maps: Add anchor to gesture handling docs link

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#841]
<img width="435" alt="edit_page_ _siteorigin_ _wordpress" src="https://user-images.githubusercontent.com/789159/53632664-3b1db980-3c1e-11e9-8768-030f5b87a52e.png">

Change the "click here" documentation link to <code>https://siteorigin.com/widgets-bundle/google-maps-widget/#gesture-handling</code>. The heading doesn't exist yet but I'll create it. That way users can find out quickly what these mean.

**Comment by braamgenis** [comment]
Ah, yeah there was a slight misunderstanding. That link was supposed to point to the Google Maps API docs [here](https://developers.google.com/maps/documentation/javascript/interaction#gestureHandling), so that we don't have to duplicate their docs. Can point it to our docs if there's something else we need to add?

Also, just FYI, these changes haven't been released yet. The release PR is #839 if you have any feedback.

**Comment by Misplon** [comment]
Thanks. I didn't realize this wasn't live yet. Let's rather link to: https://siteorigin.com/widgets-bundle/google-maps-widget/#gesture-handling. I checked the explanations and they are too long to put a summary next to each item which would have been ideal.

**Comment by Misplon** [comment]
I made a new "get your API key" screencast. Not my best as a bit out of practice but good enough. Google have made the process much easier. Great to see that.
