### ISSUE TITLE
Icons briefly load as emojis in iOS Safari

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#857]
Icons, in this case, Elegant Line Icons, briefly load as emojis in iOS Safari before changing to icons.

<img width="462" alt="emoji" src="https://user-images.githubusercontent.com/789159/56092384-d52e7e00-5ebb-11e9-8a2f-59cb6c681cba.png">
<img width="468" alt="icon" src="https://user-images.githubusercontent.com/789159/56092385-d52e7e00-5ebb-11e9-9f01-d2daf9077791.png">

Is there perhaps a small change we can make to prevent this? 
https://stackoverflow.com/questions/32915485/how-to-prevent-unicode-characters-from-rendering-as-emoji-in-html-from-javascrip

**Comment by Misplon** [comment]
Currently unable to replicate. My demo layout: https://siteorigin.com/thread/bug-report-siteorigin-features-icons-show-as-emoji-on-ios-safari/.

**Comment by Geordon** [comment]
Using Safari on my iphone, I see the same issue on the demo site.  See attached.

<img src="https://www.icloud.com/iclouddrive/0IuY71bPr-dm0NhI_F3_Vj4FQ#IMG%5F0302" alt="Screen cap showing icon/emoji bug on iOS Safari" />

I am only finding that this issue happens on Safari for iOS, not on other iOS browsers, and not at all on desktop browsers.  Since this is happening on two different websites with the same icons, and only with iOS Safari, I believe that this is a rendering issue only with Safari on iOS.

Also, since I was able to reproduce the issue on the demo website, I have not made any changes to my website theme or plugins at this time.  I will if you still want me to, but since it happened on the demo site as well, under the same conditions (iOS Safari), it seems to be happening regardless of what plugins I have active.

**Comment by Misplon** [comment]
Hi @Geordon 

We've attempted a patch/hotfix as recommended on the Stack Overflow topic linked above. We're unable to recreate the problem at the moment so can't test it. If you'd like to test it, please a pre-release copy of the Widgets Bundle [here](https://www.dropbox.com/s/8sss95s1hwgq835/so-widgets-bundle.1.15.5-dev.1.zip?dl=0). To make use of this version, go to Plugins, deactivate and delete the SiteOrigin Widgets Bundle. Then install the version linked above from Plugins > Add New > Upload Plugin > Activate. If possible, please let us know how it goes. Thanks.

**Comment by Misplon** [comment]
[so-widgets-bundle.1.15.5-dev.1.zip](https://github.com/siteorigin/so-widgets-bundle/files/3108712/so-widgets-bundle.1.15.5-dev.1.zip)

Here is the pre-release version to download to your ZIP file. This might be easier to download than the Dropbox link above. Thanks.

**Comment by Geordon** [comment]
I was able to get that installed a few minutes ago, and the result is the same ONLY on iPhone Safari.  iPad Safari shows the icons as expected.

Both my site and the demo site show the emoji icons on iPhone, but not on the iPad.  I'm sorry, I don't know if this was the case with the release version of the plugin.  On the plus side, we're narrowing things down.  I have not been able to observe the emoji changing to icons on the iPhone, even after several minutes on the page.

**Comment by Misplon** [comment]
Thanks for the update. 

Our demo page isn't running this fix at the moment.

I'm, unfortunately still unable to replicate the problem your site in iOS Safari, I've cleared the browsing data and am using a private browsing window. I'm using iOS 12.2, which version are you using?

At this stage, it's worth checking for alternatives, does the issue persist if you change your icons from Elegant Line Icons to one of the other font families available?

Thanks for your help, it's really challenging to work a problem we can't see. Appreciate it!

**Comment by Geordon** [comment]
I'm glad to help.  I just had my wife check with her iPhone, which is the same as mine (iPhone 6+, iOS 12.2) and she says that the problem isn't showing for her. 

When she told me that, I realized that there is one difference between out phones:  I have some content blockers turned on!  When I turned them off, the problem disappeared and the icons showed as expected!

If you would like to continue troubleshooting, I'd be more than glad to work with you.  It might be interesting and possibly useful to figure out where the problem is coming from.

Let me know how you would like to proceed!

**Comment by Misplon** [comment]
Super, thanks for troubleshooting. 

I think in AdBlock Plus (the premium version) you can stop this from happening as follows:

> If you use Adblock Plus (ABP), disable the option to remove social media buttons.

We're a small team so it's a bit tough for us to investigate this much further. One option might be to see if AdBlock is blocking all icon families, perhaps one of the other icon families won't be blocked. Font Awesome, for example, might not be blocked: https://help.getadblock.com/support/solutions/articles/6000148708-adblock-blocks-font-awesome-social-media-icons.

**Comment by Geordon** [comment]
On my iPhone, I’m using Blocker X, so the AdBlock instructions are not
likely to help much.

I’d be glad to take this up with the developer for my blocker, but I’m
thinking I need to know what the URL for the icons look like.  IF you can
provide me with those, I’d be ever so grateful, and I’ll let you know what
I find on that end.

-- 
Geordon VanTassle
Sent with Airmail

On April 23, 2019 at 3:12:56 PM, Andrew Misplon (notifications@github.com)
wrote:

Super, thanks for troubleshooting.

I think in AdBlock Plus (the premium version) you can stop this from
happening as follows:

If you use Adblock Plus (ABP), disable the option to remove social media
buttons.

We're a small team so it's a bit tough for us to investigate this much
further. One option might be to see if AdBlock is blocking all icon
families, perhaps one of the other icon families won't be blocked. Font
Awesome, for example, might not be blocked:
https://help.getadblock.com/support/solutions/articles/6000148708-adblock-blocks-font-awesome-social-media-icons
.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/siteorigin/so-widgets-bundle/issues/857#issuecomment-485956538>,
or mute the thread

**Comment by Misplon** [comment]
Thanks :)

The Elegant Line Icon pack is available here: https://www.elegantthemes.com/blog/freebie-of-the-week/free-line-style-icons

**Comment by Misplon** [comment]
Thanks again for the feedback. If any questions arise in the future, please let us know on the forum: https://siteorigin.com/thread. Cheers :)
