### ISSUE TITLE
Image IE 11: When destination URL is set, larger images can exceed parent container

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#864]
When a destination URL is set, larger images can exceed parent container for users using IE 11. neither the Bound or Full Width settings prevent this from happening.

With a Destination URL set:
![](https://i.imgur.com/UVgCuKT.png)

Without a Destination URL set:
![](https://i.imgur.com/i8i0SRb.png)

[Test Layout](https://drive.google.com/a/siteorigin.com/uc?id=1ezEJO4DYjLIIOb8tjuMTwTzBld-imt74)
[Test Image](https://i.imgur.com/DiBG6uU.png)

**Comment by AlexGStapleton** [comment]
This appears to be linked to the flex change.

**Comment by Misplon** [comment]
@AlexGStapleton If possible, could you provide a demo layout that Braam could load up and see the issue? Perhaps with the media URL stored on the demo.siteorigin.com server so that the images and everything are there, ready to go.

@braamgenis If we could perhaps check this out with p1 motivations next week, that would be epic. Thanks mate.

**Comment by Misplon** [comment]
Epic! @braamgenis Thanks for hitting this one quickly, appreciate it.
