### ISSUE TITLE
Investigate integration for Redis Object Cache

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#868]
A user has reported that SiteOrigin Widgets saved in theme widget areas aren't clearing the Redis Object Cache on save. SiteOrigin Widgets saved in pages or posts seem to do so fine.

Reporting topic: https://wordpress.org/support/topic/bug-conflict-with-reddis/.

**Comment by shanemarsh28** [comment]
Ok Just to update you, we are testing a solution provided by the guys who built the Reddis plugin. They believe the issue is being caused by a race condition within alloptions and advised adding a patch within mu-plugins folder that clears the cache on WP load. 

In our testing this has been enough to resolve the problem. We have not detected any further issues with saving within your plugin or anywhere else.

Discussion group is here: https://wordpress.org/support/topic/cant-save-setting-of-some-plugins/
Info regarding the bug is here: https://core.trac.wordpress.org/ticket/31245
The patch we applied is here: https://github.com/mihdan/mihdan-ticket-31245-patch

I would happily regard this issue as resolved. Thank you for your time.

**Comment by Misplon** [comment]
Hi Shane

Thanks for all the effort and providing detailed feedback, it's most appreciated. I'm really glad to hear you were able to make progress. 

Cheers for now :)
