### ISSUE TITLE
Image Grid: Maximum Image Width Setting Locked to px

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#878]
The Maximum image width setting allows you to select differnet units of measurement but this is always ignored in favor of `px`.

**Comment by braamgenis** [comment]
This is due to [this change](https://github.com/siteorigin/so-widgets-bundle/pull/740/files#diff-5dc0788cfdcadef91d4c706d20d0075bR97). It seems those fields weren't simply used as measurement values, so a deal more work would be required to figure out how non-pixel values could be used in the front end calculation done [here](https://github.com/siteorigin/so-widgets-bundle/pull/740/files#diff-5dc0788cfdcadef91d4c706d20d0075bR97). A simpler option would be to simply revert to using `number` fields and making it clear we currently only support pixel values there.

**Comment by AlexGStapleton** [comment]
This is the first time someone has reported this so I think changing that field back to a number field may be the best call.
