### ISSUE TITLE
Slider: Add height settings as we have with the Hero

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#967]
Add the same height settings that we have in the Hero widget to the slider widget.

@AlexGStapleton Thoughts on this one?

**Comment by AlexGStapleton** [comment]
This sort of setting will rely on the user specifying a height that's appropriate to the images they selected. If it's not, the image will be distorted. It's not ideal, but to avoid any frustrations, I feel it's best if we continue to recommend the Hero widget when a static height is needed due to the lower barrier to entry. Does that make sense?

**Comment by Misplon** [comment]
Sounds good.
